name: Ascii artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Run commands   
              run: | 
                echo "Hello world"
                ls -ltra
                cat README.md
            - name: Run dragon
              run: cowsay -f dragon "Run for cover.... I am a Dragooon" >> dragoon.txt
            
            - name: Test file exists
              run: |
               grep -i dragon
               cat dragoon.txt
               ls -la
                    
